### ISSUE TITLE
Python Version Requirement?

### ISSUE THREAD

**Issue by Nick-SDB** [igamenovoer/PeiDocker#1]
# Describe the issue
I was trying to create a project with the following command from the instruction:

`python -m pei_docker.pei create -p ../my_project/build/`

# Output

```
Traceback (most recent call last):
  File "/path_to_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/path_to_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./PeiDocker/pei_docker/pei.py", line 12, in <module>
    from pei_docker.config_processor import *
  File "./PeiDocker/pei_docker/config_processor.py", line 9, in <module>
    from pei_docker.user_config import *
  File "./PeiDocker/pei_docker/user_config.py", line 117, in <module>
    class ImageConfig:
  File "./PeiDocker/pei_docker/user_config.py", line 118, in ImageConfig
    base : str | None = field(default=None)
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

# Versions
Ubuntu 22.04
Python 3.9
PeiDocker [#544fd71](https://github.com/igamenovoer/PeiDocker/commit/544fd713b41c95401cf758c790e33a0931baa188)

**Comment by igamenovoer** [comment]
just use the latest python that supports all kinds of fancy syntax
